### ISSUE TITLE
Gráfico incorrecto con grabación a 0

### ISSUE THREAD

**Issue by Mariaojruiz** [Mariaojruiz/GESPRO_GESTIONTAREAS#17]
Cuando todos los registros de la grabación están a 0 el gráfico no se construye correctamente. 

![poner en la 178](https://user-images.githubusercontent.com/44766553/48316908-04c61b00-e5ea-11e8-8626-d5b44daf6f2e.jpeg)

**Comment by mor1001** [comment]
![poner en la 178](https://user-images.githubusercontent.com/44766553/48316908-04c61b00-e5ea-11e8-8626-d5b44daf6f2e.jpeg)
