### ISSUE TITLE
Pasar memoria doc a Latex

### ISSUE THREAD

**Issue by Mariaojruiz** [Mariaojruiz/GESPRO_GESTIONTAREAS#18]
- Revisar imágenes
- Revisar bibliografía
- bibentry ([https://gking.harvard.edu/files/bibentry2.pdf](url)).

### Documentación

- [x] Resumen
- [x] Introducción
- [x] Objetivos del proyecto
- [x] Conceptos teóricos
- [x] Técnicas y herramientas
- [x] Aspectos relevantes
- [x] Trabajos relacionados
- [x] Conclusiones y Líneas de trabajo futuras

**Comment by mor1001** [comment]
- Revisar imágenes

- Revisar bibliografía

- bibentry ([https://gking.harvard.edu/files/bibentry2.pdf](url)).

### Documentación

- [ ] Resumen

- [ ] Introducción

- [ ] Objetivos del proyecto

- [ ] Conceptos teóricos

- [ ] Técnicas y herramientas

- [ ] Aspectos relevantes

- [ ] Trabajos relacionados

- [ ] Conclusiones y Líneas de trabajo futuras

**Comment by Mariaojruiz** [comment]
Expresión regular para corregir las referencias:

- Buscar: `(\{\[\})([\w:\\]+)(\{\]\}\\\_)`
- Reemplazar por: `\\citep{\2}`

Ej:`{[}art:campbell2005{]}\_ -> \citep{art:campbell2005}`

----

Expresión regular para corregir las imágenes:
- Buscar: `(\\includegraphics{..\/..\/img\/)(\w*)(.\w*\})`
- Reemplazar por:  `\\imagen{\2}{descripción...}`

Ej: `\includegraphics{../../img/s2.png} -> \imagen{s2}{descripción...}}`

**Comment by Mariaojruiz** [comment]
### Cheat-sheet plantilla
#### Rutas de ficheros / paquetes
`\ruta{C:/Windows/System32}`

 #### Imágenes
Imagen en el sitio introducido:

`\imagen{nombre-img}{Descripción...}`
Imagen flotante:

`\imagenflotante{nombre-img}{Descripción...}`

| El nombre de la imagen sin extensión

**Comment by Mariaojruiz** [comment]
added a commit that referenced this issue
Convert to latex points 1 and 2

**Comment by Mariaojruiz** [comment]
added a commit that referenced this issue
Convert to latex point 3

**Comment by Mariaojruiz** [comment]
added a commit that referenced this issue 
convert to latex point 4

**Comment by Mariaojruiz** [comment]
added a commit that referenced this issue
convert to latex point 5

**Comment by Mariaojruiz** [comment]
added a commit that referenced this issue
convert to latex point 6

**Comment by Mariaojruiz** [comment]
added a commit that referenced this issue
convert to latex point 7

**Comment by Mariaojruiz** [comment]
added a commit that referenced this issue 
Improve references
